### PR TITLE
style: allow version ~>4.59

### PR DESCRIPTION
**Pull request by titouan-joseph**
Hello, 

We are facing to version mismatch, can you change the requirement as follow to allow 4.x version upper than 4.59 ?

### CODE REVIEW

**Comment by titouan-joseph** [comment]
Hello @jmolnar-zscaler,

Can you have a look to this proposition?

**Comment by titouan-joseph** [comment]
Hi @eliassun, @jmolnar-zscaler , @vkrishnamurthy-zscaler

A review or any feedback would be appreciated 

Thank you

**Comment by David7660** [comment]
Can someone look at this PR ? I'm facing version mismatch as well.

**Comment by jmolnar-zscaler** [comment]
@David7660 @titouan-joseph AWS provider support > 4.59.x and 5.x.y is included in the next repo release. In the meantime, feel free to fork this repo and update your modules to any 4.x.y provider your environment requires. There are a could minor changes required for 5.x support though fyi

**Comment by titouan-joseph** [comment]
> @David7660 @titouan-joseph AWS provider support > 4.59.x and 5.x.y is included in the next repo release. In the meantime, feel free to fork this repo and update your modules to any 4.x.y provider your environment requires. There are a could minor changes required for 5.x support though fyi

Hi @jmolnar-zscalern,

Thanks for your response.
When the new release is planned ?

**Comment by jmolnar-zscaler** [comment]
> > @David7660 @titouan-joseph AWS provider support > 4.59.x and 5.x.y is included in the next repo release. In the meantime, feel free to fork this repo and update your modules to any 4.x.y provider your environment requires. There are a could minor changes required for 5.x support though fyi
> 
> Hi @jmolnar-zscalern,
> 
> Thanks for your response. When the new release is planned ?

v.1.0.0 of the module is out now. https://github.com/zscaler/terraform-aws-cloud-connector-modules/releases

**Pull request closed without merging**
